/**
 * '가짜 예술가 찾기' 제시어 (서버 전용, 독자 작성)
 *
 * ⚠ 이 파일은 워커에서만 import 한다. src/ 나 shared/ 에서 가져오면 제시어가 학생 브라우저로 새어 나간다.
 *    tests/unit/fakeArtist.test.ts 가 그런 import 가 없는지 검사한다.
 *
 * 짧고 그림으로 그릴 수 있는 일반 명사 위주로 골랐다. 기존 보드게임의 카드 목록을 옮기지 않았다.
 * 각 항목: [id 꼬리, 제시어, ...허용 동의어]. 정답 판정은 shared/fakeArtist.ts 의 isAcceptedAnswer.
 */
import type { FaCategoryId } from '@shared/fakeArtist';

type Row = readonly [string, string, ...string[]];

const RAW: Record<FaCategoryId, readonly Row[]> = {
  animal: [
    ['cat', '고양이', '냥이', '야옹이'],
    ['dog', '강아지', '개', '멍멍이'],
    ['rabbit', '토끼'],
    ['elephant', '코끼리'],
    ['giraffe', '기린'],
    ['lion', '사자'],
    ['tiger', '호랑이', '범'],
    ['penguin', '펭귄'],
    ['turtle', '거북이', '거북'],
    ['snake', '뱀'],
    ['monkey', '원숭이'],
    ['pig', '돼지'],
    ['cow', '소', '젖소'],
    ['horse', '말'],
    ['sheep', '양'],
    ['chicken', '닭', '병아리'],
    ['duck', '오리'],
    ['owl', '부엉이', '올빼미'],
    ['octopus', '문어'],
    ['shark', '상어'],
    ['whale', '고래'],
    ['snail', '달팽이'],
    ['butterfly', '나비'],
    ['ant', '개미'],
    ['spider', '거미'],
    ['kangaroo', '캥거루'],
    ['bear', '곰'],
    ['squirrel', '다람쥐'],
  ],
  food: [
    ['apple', '사과'],
    ['banana', '바나나'],
    ['watermelon', '수박'],
    ['grape', '포도'],
    ['strawberry', '딸기'],
    ['pizza', '피자'],
    ['hamburger', '햄버거', '버거'],
    ['gimbap', '김밥'],
    ['ramen', '라면'],
    ['icecream', '아이스크림', '아이스크림콘'],
    ['cake', '케이크', '케익'],
    ['donut', '도넛', '도너츠', '도나쓰'],
    ['tteokbokki', '떡볶이'],
    ['chicken', '치킨', '통닭'],
    ['hotdog', '핫도그'],
    ['riceball', '주먹밥', '삼각김밥'],
    ['friedegg', '계란프라이', '달걀프라이', '계란후라이', '달걀후라이'],
    ['bread', '식빵', '빵'],
    ['carrot', '당근'],
    ['corn', '옥수수'],
    ['mushroom', '버섯'],
    ['pineapple', '파인애플'],
    ['sushi', '초밥', '스시'],
    ['dumpling', '만두'],
    ['cottoncandy', '솜사탕'],
    ['lollipop', '막대사탕', '사탕'],
    ['sandwich', '샌드위치'],
  ],
  vehicle: [
    ['car', '자동차', '차', '승용차'],
    ['bus', '버스'],
    ['train', '기차', '열차'],
    ['airplane', '비행기'],
    ['ship', '배', '선박'],
    ['bicycle', '자전거'],
    ['motorcycle', '오토바이'],
    ['helicopter', '헬리콥터', '헬기'],
    ['rocket', '로켓'],
    ['submarine', '잠수함'],
    ['truck', '트럭'],
    ['firetruck', '소방차'],
    ['ambulance', '구급차', '앰뷸런스'],
    ['policecar', '경찰차'],
    ['taxi', '택시'],
    ['subway', '지하철', '전철'],
    ['balloon', '열기구'],
    ['skateboard', '스케이트보드'],
    ['scooter', '킥보드', '킥스쿠터'],
    ['yacht', '요트'],
    ['canoe', '카누', '카약'],
    ['tractor', '트랙터'],
    ['excavator', '굴착기', '포클레인', '포크레인'],
    ['cablecar', '케이블카'],
    ['stroller', '유모차'],
    ['sled', '썰매'],
    ['spaceship', '우주선'],
  ],
  household: [
    ['umbrella', '우산'],
    ['scissors', '가위'],
    ['toothbrush', '칫솔'],
    ['clock', '시계'],
    ['glasses', '안경'],
    ['chair', '의자'],
    ['bed', '침대'],
    ['mirror', '거울'],
    ['cup', '컵'],
    ['spoon', '숟가락', '수저'],
    ['fork', '포크'],
    ['pot', '냄비'],
    ['kettle', '주전자'],
    ['bulb', '전구'],
    ['key', '열쇠'],
    ['lock', '자물쇠'],
    ['comb', '빗'],
    ['towel', '수건'],
    ['pillow', '베개'],
    ['tv', '텔레비전', '티비', 'tv'],
    ['fridge', '냉장고'],
    ['fan', '선풍기'],
    ['phone', '휴대폰', '핸드폰', '스마트폰', '전화기'],
    ['pencil', '연필'],
    ['book', '책'],
    ['bag', '가방', '책가방'],
    ['sock', '양말'],
    ['hat', '모자'],
    ['glove', '장갑'],
  ],
  place: [
    ['school', '학교'],
    ['hospital', '병원'],
    ['park', '공원'],
    ['beach', '해변', '바닷가', '해수욕장'],
    ['mountain', '산'],
    ['library', '도서관'],
    ['amusement', '놀이공원', '유원지'],
    ['pool', '수영장'],
    ['zoo', '동물원'],
    ['airport', '공항'],
    ['station', '기차역', '역'],
    ['campsite', '캠핑장'],
    ['bakery', '빵집', '제과점'],
    ['policestation', '경찰서'],
    ['firestation', '소방서'],
    ['postoffice', '우체국'],
    ['cinema', '영화관', '극장'],
    ['store', '편의점'],
    ['museum', '박물관'],
    ['field', '운동장'],
    ['playground', '놀이터'],
    ['desert', '사막'],
    ['island', '섬'],
    ['castle', '성', '궁전'],
    ['lighthouse', '등대'],
    ['farm', '농장'],
    ['market', '시장'],
  ],
  nature: [
    ['sun', '해', '태양'],
    ['moon', '달'],
    ['star', '별'],
    ['cloud', '구름'],
    ['rain', '비'],
    ['snow', '눈', '눈송이'],
    ['rainbow', '무지개'],
    ['lightning', '번개'],
    ['wind', '바람'],
    ['tree', '나무'],
    ['flower', '꽃'],
    ['leaf', '나뭇잎', '잎', '잎사귀'],
    ['volcano', '화산'],
    ['river', '강', '시냇물'],
    ['waterfall', '폭포'],
    ['wave', '파도'],
    ['rock', '바위', '돌'],
    ['cactus', '선인장'],
    ['sprout', '새싹'],
    ['ice', '얼음'],
    ['cave', '동굴'],
    ['lake', '호수'],
    ['sand', '모래'],
    ['fire', '불', '모닥불'],
    ['pond', '연못'],
    ['sunflower', '해바라기'],
    ['rose', '장미'],
    ['tornado', '회오리', '토네이도', '회오리바람'],
  ],
  job: [
    ['doctor', '의사'],
    ['nurse', '간호사'],
    ['police', '경찰', '경찰관'],
    ['firefighter', '소방관'],
    ['teacher', '선생님', '교사'],
    ['chef', '요리사', '셰프'],
    ['farmer', '농부'],
    ['painter', '화가'],
    ['singer', '가수'],
    ['astronaut', '우주비행사', '우주인'],
    ['pilot', '조종사', '파일럿'],
    ['fisher', '어부'],
    ['hairdresser', '미용사'],
    ['baker', '제빵사'],
    ['mailcarrier', '집배원', '우편배달부'],
    ['scientist', '과학자'],
    ['photographer', '사진작가', '사진사'],
    ['magician', '마술사'],
    ['clown', '광대', '어릿광대'],
    ['carpenter', '목수'],
    ['driver', '운전기사', '기사'],
    ['footballer', '축구선수'],
    ['ballerina', '발레리나', '무용수'],
    ['judge', '판사'],
    ['vet', '수의사'],
    ['reporter', '기자'],
    ['detective', '탐정'],
  ],
  sport: [
    ['soccer', '축구'],
    ['baseball', '야구'],
    ['basketball', '농구'],
    ['volleyball', '배구'],
    ['pingpong', '탁구'],
    ['tennis', '테니스'],
    ['badminton', '배드민턴'],
    ['swimming', '수영'],
    ['ski', '스키'],
    ['skate', '스케이트', '스케이팅'],
    ['jumprope', '줄넘기'],
    ['running', '달리기', '육상'],
    ['taekwondo', '태권도'],
    ['ssireum', '씨름'],
    ['bowling', '볼링'],
    ['golf', '골프'],
    ['archery', '양궁', '활쏘기'],
    ['boxing', '권투', '복싱'],
    ['gymnastics', '체조'],
    ['surfing', '서핑', '파도타기'],
    ['yoga', '요가'],
    ['snowboard', '스노보드'],
    ['judo', '유도'],
    ['cycling', '자전거타기', '사이클'],
    ['hulahoop', '훌라후프'],
    ['hiking', '등산'],
    ['fencing', '펜싱'],
  ],
};

export interface FaWord {
  wordId: string;
  categoryId: FaCategoryId;
  word: string;
  /** 정답으로 인정하는 표기 (제시어 자신 포함) */
  accepted: string[];
}

export const FA_WORDS: Record<FaCategoryId, FaWord[]> = Object.fromEntries(
  Object.entries(RAW).map(([categoryId, rows]) => [
    categoryId,
    rows.map(([tail, word, ...syn]) => ({ wordId: `${categoryId}.${tail}`, categoryId: categoryId as FaCategoryId, word, accepted: [word, ...syn] })),
  ]),
) as Record<FaCategoryId, FaWord[]>;

export function faWordCount(): number {
  return Object.values(FA_WORDS).reduce((n, list) => n + list.length, 0);
}

/**
 * 분류에서 제시어 하나를 뽑는다. 이 방에서 최근에 나온 제시어는 피한다
 * (분류의 모든 제시어를 최근에 썼다면 제한을 풀고 전체에서 뽑는다).
 */
export function pickFaWord(categoryId: FaCategoryId, recentWordIds: readonly string[], random: () => number): FaWord {
  const all = FA_WORDS[categoryId];
  const recent = new Set(recentWordIds);
  const fresh = all.filter((w) => !recent.has(w.wordId));
  const pool = fresh.length > 0 ? fresh : all;
  return pool[Math.floor(random() * pool.length)]!;
}
